/*     */ package net.craftigames.polar.common.core.sound;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ @Deprecated
/*     */ public enum PolarSound
/*     */ {
/*  13 */   AMBIENCE_CAVE("ambient.cave.cave"),
/*  14 */   AMBIENCE_RAIN("ambient.weather.rain"),
/*  15 */   AMBIENCE_THUNDER("ambient.weather.thunder"),
/*  16 */   HURT_FLESH("game.neutral.hurt"),
/*  17 */   FALL_BIG("game.neutral.hurt.fall.big"),
/*  18 */   FALL_SMALL("game.neutral.hurt.fall.small"),
/*  19 */   DIG_WOOL("dig.cloth"),
/*  20 */   DIG_GRASS("dig.grass"),
/*  21 */   DIG_GRAVEL("dig.gravel"),
/*  22 */   DIG_SAND("dig.sand"),
/*  23 */   DIG_SNOW("dig.snow"),
/*  24 */   DIG_STONE("dig.stone"),
/*  25 */   DIG_WOOD("dig.wood"),
/*  26 */   FIRE("fire.fire"),
/*  27 */   FIRE_IGNITE("fire.ignite"),
/*  28 */   FIREWORK_BLAST("fireworks.blast"),
/*  29 */   FIREWORK_BLAST2("fireworks.blast_far"),
/*  30 */   FIREWORK_LARGE_BLAST("fireworks.largeBlast"),
/*  31 */   FIREWORK_LARGE_BLAST2("fireworks.largeBlast_far"),
/*  32 */   FIREWORK_TWINKLE("fireworks.twinkle"),
/*  33 */   FIREWORK_TWINKLE2("fireworks.twinkle_far"),
/*  34 */   FIREWORK_LAUNCH("fireworks.launch"),
/*  35 */   SPLASH2("game.neutral.swim.splash"),
/*  36 */   SWIM("game.neutral.swim"),
/*  37 */   WATER("liquid.water"),
/*  38 */   LAVA("liquid.lava"),
/*  39 */   LAVA_POP("liquid.lavapop"),
/*  40 */   MINECART_BASE("minecart.base"),
/*  41 */   MINECART_INSIDE("minecart.inside"),
/*  42 */   BAT_DEATH("mob.bat.death"),
/*  43 */   BAT_HURT("mob.bat.hurt"),
/*  44 */   BAT_IDLE("mob.bat.idle"),
/*  45 */   BAT_LOOP("mob.bat.loop"),
/*  46 */   BAT_TAKEOFF("mob.bat.takeoff"),
/*  47 */   BLAZE_BREATH("mob.blaze.breathe"),
/*  48 */   BLAZE_DEATH("mob.blaze.death"),
/*  49 */   BLAZE_HIT("mob.blaze.hit"),
/*  50 */   CAT_HISS("mob.cat.hiss"),
/*  51 */   CAT_HIT("mob.cat.hitt"),
/*  52 */   CAT_MEOW("mob.cat.meow"),
/*  53 */   CAT_PURR("mob.cat.purr"),
/*  54 */   CAT_PURREOW("mob.cat.purreow"),
/*  55 */   CHICKEN_IDLE("mob.chicken.say"),
/*  56 */   CHICKEN_HURT("mob.chicken.hurt"),
/*  57 */   CHICKEN_EGG_POP("mob.chicken.plop"),
/*  58 */   CHICKEN_WALK("mob.chicken.step"),
/*  59 */   COW_HURT("mob.cow.hurt"),
/*  60 */   COW_IDLE("mob.cow.say"),
/*  61 */   COW_WALK("mob.cow.step"),
/*  62 */   CREEPER_DEATH("mob.creeper.death"),
/*  63 */   CREEPER_HISS("mob.creeper.say"),
/*  64 */   ENDERDRAGON_DEATH("mob.enderdragon.end"),
/*  65 */   ENDERDRAGON_GROWL("mob.enderdragon.growl"),
/*  66 */   ENDERDRAGON_HIT("mob.enderdragon.hit"),
/*  67 */   ENDERDRAGON_WINGS("mob.enderdragon.wings"),
/*  68 */   ENDERMAN_DEATH("mob.endermen.death"),
/*  69 */   ENDERMAN_HIT("mob.endermen.hit"),
/*  70 */   ENDERMAN_IDLE("mob.endermen.idle"),
/*  71 */   ENDERMAN_TELEPORT("mob.endermen.portal"),
/*  72 */   ENDERMAN_SCREAM("mob.endermen.scream"),
/*  73 */   ENDERMAN_STARE("mob.endermen.stare"),
/*  74 */   GHAST_SCREAM2("mob.ghast.affectionate_scream"),
/*  75 */   GHAST_CHARGE("mob.ghast.charge"),
/*  76 */   GHAST_DEATH("mob.ghast.death"),
/*  77 */   GHAST_FIREBALL("mob.ghast.fireball"),
/*  78 */   GHAST_MOAN("mob.ghast.moan"),
/*  79 */   GHAST_SCREAM("mob.ghast.scream"),
/*  80 */   HORSE_ANGRY("mob.horse.angry"),
/*  81 */   HORSE_ARMOR("mob.horse.armor"),
/*  82 */   HORSE_BREATHE("mob.horse.breathe"),
/*  83 */   HORSE_DEATH("mob.horse.death"),
/*  84 */   HORSE_GALLOP("mob.horse.gallop"),
/*  85 */   HORSE_HIT("mob.horse.hit"),
/*  86 */   HORSE_IDLE("mob.horse.idle"),
/*  87 */   HORSE_JUMP("mob.horse.jump"),
/*  88 */   HORSE_LAND("mob.horse.land"),
/*  89 */   HORSE_SADDLE("mob.horse.leather"),
/*  90 */   HORSE_SOFT("mob.horse.soft"),
/*  91 */   HORSE_WOOD("mob.horse.wood"),
/*  92 */   DONKEY_ANGRY("mob.horse.donkey.angry"),
/*  93 */   DONKEY_DEATH("mob.horse.donkey.death"),
/*  94 */   DONKEY_HIT("mob.horse.donkey.hit"),
/*  95 */   DONKEY_IDLE("mob.horse.donkey.idle"),
/*  96 */   HORSE_SKELETON_DEATH("mob.horse.skeleton.death"),
/*  97 */   HORSE_SKELETON_HIT("mob.horse.skeleton.hit"),
/*  98 */   HORSE_SKELETON_IDLE("mob.horse.skeleton.idle"),
/*  99 */   HORSE_ZOMBIE_DEATH("mob.horse.zombie.death"),
/* 100 */   HORSE_ZOMBIE_HIT("mob.horse.zombie.hit"),
/* 101 */   HORSE_ZOMBIE_IDLE("mob.horse.zombie.idle"),
/* 102 */   IRONGOLEM_DEATH("mob.irongolem.death"),
/* 103 */   IRONGOLEM_HIT("mob.irongolem.hit"),
/* 104 */   IRONGOLEM_THROW("mob.irongolem.throw"),
/* 105 */   IRONGOLEM_WALK("mob.irongolem.walk"),
/* 106 */   MAGMACUBE_WALK("mob.magmacube.small"),
/* 107 */   MAGMACUBE_WALK2("mob.magmacube.big"),
/* 108 */   MAGMACUBE_JUMP("mob.magmacube.jump"),
/* 109 */   PIG_IDLE("mob.pig.say"),
/* 110 */   PIG_DEATH("mob.pig.death"),
/* 111 */   PIG_WALK("mob.pig.step"),
/* 112 */   SHEEP_IDLE("mob.sheep.say"),
/* 113 */   SHEEP_SHEAR("mob.sheep.shear"),
/* 114 */   SHEEP_WALK("mob.sheep.step"),
/* 115 */   SILVERFISH_HIT("mob.silverfish.hit"),
/* 116 */   SILVERFISH_KILL("mob.silverfish.kill"),
/* 117 */   SILVERFISH_IDLE("mob.silverfish.say"),
/* 118 */   SILVERFISH_WALK("mob.silverfish.step"),
/* 119 */   SKELETON_IDLE("mob.skeleton.say"),
/* 120 */   SKELETON_DEATH("mob.skeleton.death"),
/* 121 */   SKELETON_HURT("mob.skeleton.hurt"),
/* 122 */   SKELETON_WALK("mob.skeleton.step"),
/* 123 */   SLIME_ATTACK("mob.slime.attack"),
/* 124 */   SLIME_WALK("mob.slime.small"),
/* 125 */   SLIME_WALK2("mob.slime.big"),
/* 126 */   SPIDER_IDLE("mob.spider.say"),
/* 127 */   SPIDER_DEATH("mob.spider.death"),
/* 128 */   SPIDER_WALK("mob.spider.step"),
/* 129 */   VILLAGER_DEATH("mob.villager.death"),
/* 130 */   VILLAGER_HAGGLE("mob.villager.haggle"),
/* 131 */   VILLAGER_HIT("mob.villager.hit"),
/* 132 */   VILLAGER_IDLE("mob.villager.idle"),
/* 133 */   VILLAGER_NO("mob.villager.no"),
/* 134 */   VILLAGER_YES("mob.villager.yes"),
/* 135 */   WITHER_DEATH("mob.wither.death"),
/* 136 */   WITHER_HURT("mob.wither.hurt"),
/* 137 */   WITHER_IDLE("mob.wither.idle"),
/* 138 */   WITHER_SHOOT("mob.wither.shoot"),
/* 139 */   WITHER_SPAWN("mob.wither.spawn"),
/* 140 */   WOLF_BARK("mob.wolf.bark"),
/* 141 */   WOLF_DEATH("mob.wolf.death"),
/* 142 */   WOLF_GROWL("mob.wolf.growl"),
/* 143 */   WOLF_HOWL("mob.wolf.howl"),
/* 144 */   WOLF_HURT("mob.wolf.hurt"),
/* 145 */   WOLF_PANT("mob.wolf.panting"),
/* 146 */   WOLF_SHAKE("mob.wolf.shake"),
/* 147 */   WOLF_WALK("mob.wolf.step"),
/* 148 */   WOLF_WHINE("mob.wolf.whine"),
/* 149 */   ZOMBIE_METAL("mob.zombie.metal"),
/* 150 */   ZOMBIE_WOOD("mob.zombie.wood"),
/* 151 */   ZOMBIE_WOODBREAK("mob.zombie.woodbreak"),
/* 152 */   ZOMBIE_IDLE("mob.zombie.say"),
/* 153 */   ZOMBIE_DEATH("mob.zombie.death"),
/* 154 */   ZOMBIE_HURT("mob.zombie.hurt"),
/* 155 */   ZOMBIE_INFECT("mob.zombie.infect"),
/* 156 */   ZOMBIE_UNFECT("mob.zombie.unfect"),
/* 157 */   ZOMBIE_REMEDY("mob.zombie.remedy"),
/* 158 */   ZOMBIE_WALK("mob.zombie.step"),
/* 159 */   ZOMBIE_PIG_IDLE("mob.zombiepig.zpig"),
/* 160 */   ZOMBIE_PIG_ANGRY("mob.zombiepig.zpigangry"),
/* 161 */   ZOMBIE_PIG_DEATH("mob.zombiepig.zpigdeath"),
/* 162 */   ZOMBIE_PIG_HURT("mob.zombiepig.zpighurt"),
/* 163 */   NOTE_BASS_GUITAR("note.bassattack"),
/* 164 */   NOTE_SNARE_DRUM("note.snare"),
/* 165 */   NOTE_PLING("note.pling"),
/* 166 */   NOTE_BASS("note.bass"),
/* 167 */   NOTE_PIANO("note.harp"),
/* 168 */   NOTE_BASS_DRUM("note.bd"),
/* 169 */   NOTE_STICKS("note.hat"),
/* 170 */   PORTAL("portal.portal"),
/* 171 */   PORTAL_TRAVEL("portal.travel"),
/* 172 */   PORTAL_TRIGGER("portal.trigger"),
/* 173 */   ANVIL_BREAK("random.anvil_break"),
/* 174 */   ANVIL_LAND("random.anvil_land"),
/* 175 */   ANVIL_USE("random.anvil_use"),
/* 176 */   SHOOT_ARROW("random.bow"),
/* 177 */   ARROW_HIT("random.bowhit"),
/* 178 */   ITEM_BREAK("random.break"),
/* 179 */   BURP("random.burp"),
/* 180 */   CHEST_CLOSE("random.chestclosed"),
/* 181 */   CHEST_OPEN("random.chestopen"),
/* 182 */   CLICK("random.click"),
/* 183 */   DOOR_CLOSE("random.door_close"),
/* 184 */   DOOR_OPEN("random.door_open"),
/* 185 */   DRINK("random.drink"),
/* 186 */   EAT("random.eat"),
/* 187 */   EXPLODE("random.explode"),
/* 188 */   FIZZ("random.fizz"),
/* 189 */   FUSE("creeper.primed"),
/* 190 */   GLASS("dig.glass"),
/* 191 */   LEVEL_UP("random.levelup"),
/* 192 */   ORB_PICKUP("random.orb"),
/* 193 */   ITEM_PICKUP("random.pop"),
/* 194 */   SPLASH("random.splash"),
/* 195 */   SUCCESSFUL_HIT("random.successful_hit"),
/* 196 */   WOOD_CLICK("random.wood_click"),
/* 197 */   STEP_WOOL("step.cloth"),
/* 198 */   STEP_GRASS("step.grass"),
/* 199 */   STEP_GRAVEL("step.gravel"),
/* 200 */   STEP_LADDER("step.ladder"),
/* 201 */   STEP_SAND("step.sand"),
/* 202 */   STEP_SNOW("step.snow"),
/* 203 */   STEP_STONE("step.stone"),
/* 204 */   STEP_WOOD("step.wood"),
/* 205 */   PISTON_EXTEND("tile.piston.out"),
/* 206 */   PISTON_RETRACT("tile.piston.in");
/*     */   private final int id; private final String sound;
/*     */   
/* 209 */   public int getId() { return this.id; } public String getSound() {
/* 210 */     return this.sound;
/*     */   }
/*     */   PolarSound(String name) {
/* 213 */     this.id = ordinal();
/* 214 */     this.sound = name;
/*     */   }
/*     */ }


/* Location:              D:\Minecraft 伺服器資料\Pika&Jartex\PolarCommon-1.3.5-20230128.224209-66-LEAKED.jar!\net\craftigames\polar\common\core\sound\PolarSound.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */